name: Build and Deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  MD_FOLDER: .
  DEPLOY_BRANCH: vercel

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SSG repo
        uses: actions/checkout@v4
        with:
          repository: dhzdhd/jade

      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          path: garden

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Run prerequisite script
        working-directory: 'scripts'
        run: |
          node prereq.ts ${{ github.workspace }} false

      - name: Move markdown files
        run: |
          rsync -avm --include='*/' "garden/${{ env.MD_FOLDER }}/" "posts"

      - name: Copy images to static/
        run: |
          rsync -avm --include='*.png' --include='*.jpg' --include='*.jpeg' --include='*.webp' --include='*.svg' --include='*/' --exclude='*' "garden/${{ env.MD_FOLDER }}/" "static"

      - name: Remove garden
        run: rm -rf garden

      - name: Push built files to deploy branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: ${{ env.DEPLOY_BRANCH }}
          folder: .
